spring:
  datasource:
    url: jdbc:mysql://localhost:3307/twitterdb
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
